"""
Reading Notes Management System - Flask API
AI-generated REST API for book notes collection and management

This file is automatically generated by the AI-powered meta-software development system.
"""

from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import uuid
from datetime import datetime

app = Flask(__name__, static_folder='.', static_url_path='')
CORS(app)

# In-memory storage for reading notes
notes_db = []

# ============================================================================
# Health Check
# ============================================================================

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({"status": "ok", "timestamp": datetime.now().isoformat()})

# ============================================================================
# Reading Notes Endpoints
# ============================================================================

@app.route('/notes', methods=['POST'])
def add_note():
    """Add a new reading note"""
    data = request.get_json()

    # Validation
    required_fields = ['title', 'author', 'genre', 'rating', 'notes']
    for field in required_fields:
        if field not in data:
            return jsonify({"error": f"Missing required field: {field}"}), 400

    # Validate rating range
    try:
        rating = int(data['rating'])
        if rating < 1 or rating > 5:
            return jsonify({"error": "Rating must be between 1 and 5"}), 400
    except ValueError:
        return jsonify({"error": "Rating must be an integer"}), 400

    # Validate genre
    valid_genres = ['Fiction', 'Non-Fiction', 'Sci-Fi', 'Biography', 'Self-Help', 'Other']
    if data['genre'] not in valid_genres:
        return jsonify({"error": f"Invalid genre. Must be one of: {valid_genres}"}), 400

    # Create note entry
    note = {
        "id": str(uuid.uuid4()),
        "title": data['title'],
        "author": data['author'],
        "genre": data['genre'],
        "rating": rating,
        "notes": data['notes'],
        "quotes": data.get('quotes', []),
        "reading_status": data.get('reading_status', 'completed'),
        "timestamp": datetime.now().isoformat()
    }

    notes_db.append(note)

    return jsonify({
        "id": note['id'],
        "status": "created",
        "message": "Reading note added successfully",
        "timestamp": note['timestamp']
    }), 201


@app.route('/notes', methods=['GET'])
def get_all_notes():
    """Get all reading notes with optional filtering"""
    # Optional filtering
    genre = request.args.get('genre')
    status = request.args.get('status')
    min_rating = request.args.get('min_rating', type=int)

    filtered = notes_db

    if genre:
        filtered = [n for n in filtered if n['genre'] == genre]
    if status:
        filtered = [n for n in filtered if n['reading_status'] == status]
    if min_rating:
        filtered = [n for n in filtered if n['rating'] >= min_rating]

    return jsonify(filtered)


@app.route('/notes/<note_id>', methods=['GET'])
def get_note(note_id):
    """Get specific note by ID"""
    for note in notes_db:
        if note['id'] == note_id:
            return jsonify(note)
    return jsonify({"error": "Note not found"}), 404


@app.route('/notes/<note_id>', methods=['PATCH'])
def update_note(note_id):
    """Update a reading note (status, rating, add quotes)"""
    data = request.get_json()

    for note in notes_db:
        if note['id'] == note_id:
            if 'rating' in data:
                try:
                    rating = int(data['rating'])
                    if rating < 1 or rating > 5:
                        return jsonify({"error": "Rating must be between 1 and 5"}), 400
                    note['rating'] = rating
                except ValueError:
                    return jsonify({"error": "Rating must be an integer"}), 400

            if 'reading_status' in data:
                valid_statuses = ['reading', 'completed', 'abandoned']
                if data['reading_status'] not in valid_statuses:
                    return jsonify({"error": f"Invalid status. Must be one of: {valid_statuses}"}), 400
                note['reading_status'] = data['reading_status']

            if 'notes' in data:
                note['notes'] = data['notes']

            if 'quotes' in data:
                if isinstance(data['quotes'], list):
                    note['quotes'].extend(data['quotes'])
                else:
                    note['quotes'].append(data['quotes'])

            note['updated_at'] = datetime.now().isoformat()
            return jsonify(note)

    return jsonify({"error": "Note not found"}), 404


@app.route('/notes/<note_id>', methods=['DELETE'])
def delete_note(note_id):
    """Delete a reading note"""
    for i, note in enumerate(notes_db):
        if note['id'] == note_id:
            notes_db.pop(i)
            return jsonify({"status": "deleted", "id": note_id})
    return jsonify({"error": "Note not found"}), 404


# ============================================================================
# Quotes Endpoints
# ============================================================================

@app.route('/notes/<note_id>/quotes', methods=['POST'])
def add_quote(note_id):
    """Add a quote to a reading note"""
    data = request.get_json()

    if 'quote' not in data:
        return jsonify({"error": "Missing required field: quote"}), 400

    for note in notes_db:
        if note['id'] == note_id:
            quote_entry = {
                "quote": data['quote'],
                "page": data.get('page', None),
                "timestamp": datetime.now().isoformat()
            }
            note['quotes'].append(quote_entry)
            return jsonify(note)

    return jsonify({"error": "Note not found"}), 404


# ============================================================================
# Statistics Endpoints
# ============================================================================

@app.route('/stats', methods=['GET'])
def get_reading_stats():
    """Get reading statistics"""
    if not notes_db:
        return jsonify({
            "total_books": 0,
            "average_rating": 0,
            "genre_breakdown": {},
            "status_breakdown": {},
            "total_quotes": 0
        })

    total = len(notes_db)
    avg_rating = sum(n['rating'] for n in notes_db) / total

    genre_breakdown = {}
    for n in notes_db:
        genre_breakdown[n['genre']] = genre_breakdown.get(n['genre'], 0) + 1

    status_breakdown = {}
    for n in notes_db:
        status_breakdown[n['reading_status']] = status_breakdown.get(n['reading_status'], 0) + 1

    total_quotes = sum(len(n.get('quotes', [])) for n in notes_db)

    return jsonify({
        "total_books": total,
        "average_rating": round(avg_rating, 1),
        "genre_breakdown": genre_breakdown,
        "status_breakdown": status_breakdown,
        "total_quotes": total_quotes
    })


@app.route('/genres', methods=['GET'])
def get_genres():
    """Get list of available genres"""
    return jsonify({
        "genres": ['Fiction', 'Non-Fiction', 'Sci-Fi', 'Biography', 'Self-Help', 'Other']
    })


# ============================================================================
# Search Endpoint
# ============================================================================

@app.route('/search', methods=['GET'])
def search_notes():
    """Search notes by keyword in title, author, or notes content"""
    query = request.args.get('q', '').lower().strip()
    if not query:
        return jsonify({"error": "Missing search query parameter 'q'"}), 400

    results = []
    for note in notes_db:
        if (query in note['title'].lower() or
            query in note['author'].lower() or
            query in note['notes'].lower()):
            results.append(note)

    return jsonify(results)


# ============================================================================
# Frontend Serving
# ============================================================================

@app.route('/', methods=['GET'])
def index():
    """Serve frontend HTML page"""
    return send_from_directory('.', 'index.html')


# ============================================================================
# Error Handlers
# ============================================================================

@app.errorhandler(404)
def not_found(error):
    return jsonify({"error": "Resource not found"}), 404

@app.errorhandler(500)
def internal_error(error):
    return jsonify({"error": "Internal server error"}), 500

@app.errorhandler(400)
def bad_request(error):
    return jsonify({"error": "Bad request"}), 400


# ============================================================================
# Main Entry Point
# ============================================================================

if __name__ == '__main__':
    print("=" * 60)
    print("  Reading Notes Management API")
    print("  AI-Powered Meta-Software Development")
    print("=" * 60)
    print("\nEndpoints available:")
    print("  GET  /health              - Health check")
    print("  POST /notes              - Add reading note")
    print("  GET  /notes              - Get all notes (filter: genre, status, min_rating)")
    print("  GET  /notes/<id>         - Get specific note")
    print("  PATCH /notes/<id>        - Update note")
    print("  DELETE /notes/<id>       - Delete note")
    print("  POST /notes/<id>/quotes - Add quote to note")
    print("  GET  /stats              - Reading statistics")
    print("  GET  /genres             - Available genres")
    print("  GET  /search?q=keyword   - Search notes")
    print("  GET  /                   - Frontend page")
    print("\n" + "=" * 60)
    app.run(host='0.0.0.0', port=5005, debug=True)